### ISSUE TITLE
<Response [400]> issue

### ISSUE THREAD

**Issue by sean-james** [jagrosh/FrostCleverbot#11]
Hey there, I'm just having a look at your code and I've migrated it over the Discord Rewrite branch. 
I have a query probably unrelated to the code itself but I'm getting a <Response [400]> ?

![image](https://user-images.githubusercontent.com/20223951/56080012-9a611300-5df3-11e9-9916-501499ad0258.png)

**Comment by jagrosh** [comment]
Sounds like an issue with cleverbot.io, which unfortunately is something I don't have control over. I'll look into making a branch that uses some other source.
