### ISSUE TITLE
How to start up?

### ISSUE THREAD

**Issue by sourgummyes** [jagrosh/FrostCleverbot#2]
![image](https://cloud.githubusercontent.com/assets/26637455/24272986/4f7c9460-0ff6-11e7-9ee3-1a1533f51594.png) This is what happens when i try doing it in command prompt. I can give more info, but i want to use that privatly

**Comment by jagrosh** [comment]
Try `python3 -m pip install requests`

**Comment by sourgummyes** [comment]
[image: Inline image 1]this is what happens after i try. I did do the
install thing first.

**Comment by sourgummyes** [comment]
fixed it
