### ISSUE TITLE
Cleverbot isn't responding

### ISSUE THREAD

**Issue by sypion** [jagrosh/FrostCleverbot#4]
I've made sure everything was setup properly. The `API User` & `API Key` are both in the `frost.py` file correctly. The bot starts up successfully and is in my server, but when you talk to the bot, it doesn't respond back-- just sends the usual typing notification at the bottom of the chat bar.

Cleverbot.io is online; I just don't understand the problem and help would be dearly appreciated.

**Comment by jagrosh** [comment]
It's "working" for me:
![image](http://i.imgur.com/4BZW04f.png)

Cleverbot.io's server has been extremely spotty, and if the bot is not responding, it's the fault of their service being offline or extremely slow. Occasionally it seems like they switch over to a debug mode where all responses are "Hey there".

**Comment by sypion** [comment]
Well actually after finishing writing this issue, the bot responded but in a different language?
![image](https://user-images.githubusercontent.com/8906653/28551878-8f4718cc-709f-11e7-8d06-746628fea9b0.png)

**Comment by jagrosh** [comment]
That's the fault of cleverbot.io; like I mentioned, their service has been spotty at best.

**Comment by sypion** [comment]
Ah, I see. Thank you for the swift response!

**Comment by jagrosh** [comment]
I plan to eventually replace cleverbot.io with a cleverbot service of my own creation; it's in progress but I don't have any ETA at the moment.

**Comment by sypion** [comment]
Definitely keep me posted.

**Comment by Seecomp** [comment]
### *Cleverbot_ spits out a Error 524*
