### ISSUE TITLE
Launch Error

### ISSUE THREAD

**Issue by yogurtsyum** [jagrosh/FrostCleverbot#9]
When I launch the bot it says that on line 11 there is an error.

**Comment by yogurtsyum** [comment]
@jagrosh ^

**Comment by Habchy** [comment]
Have you modified the code at all? @xLengoBug5

**Comment by ghost** [comment]
Same here when i try to launch it on linux mint: the only edits i made where inserting the api keys

arte@arte-Inspiron-1545:~$ python siri.py
  File "siri.py", line 11
    async def on_ready():
        ^
SyntaxError: invalid syntax
